#ifndef FLIGHTCOMPUTER_SENSORCONFIG_H
#define FLIGHTCOMPUTER_SENSORCONFIG_H

// Count



// Constants

#define VACUUM 0
#define ATMOSPHERE 15
#define CLOSED 0
#define OPEN 1


// Connection Status Flags
#define TOTAL_CONNECTION_COUNT 6 // BE SURE TO UDPATE
#define BRAKE_NODE_HEARTBEAT_INDEX 0
#define LVDC_NODE_HEARTBEAT_INDEX 1
#define BMS_HEARTBEAT_INDEX 2
#define INTERFACE_HEARTBEAT_INDEX 3
#define ENCLOSURE_HEARTBEAT_INDEX 4
#define NAVIGATION_HEARTBEAT_INDEX 5

// Inverter Sensor Flag Indices
#define INVERTER_SENSOR_COUNT 2
#define MOTOR_TEMPERATURE_INDEX 0
#define BUS_VOLTAGE_INDEX 1

// BMS Sensor Flag Indices
#define BMS_SENSOR_COUNT 3
#define PACK_VOLTAGE_INDEX 0
#define MAX_CELL_TEMP_INDEX 1
#define SOC_INDEX 2

// Node Sensor Flag indices
#define NODE_SENSOR_COUNT 10
#define LP1_INDEX 0
#define LP2_INDEX 1
#define LP3_INDEX 2
#define LP4_INDEX 3
#define HP_INDEX  4
#define HP_TEMP_INDEX 5
#define ENCLOSURE_PRESSURE_INDEX 6
#define ENCLOSURE_TEMPERATURE_INDEX 7
#define COOLING_PRESSURE_INDEX 8
#define COOLING_TEMPERATURE_INDEX 9

// Solenoid Status indices
#define SOL1_INDEX 0
#define SOL2_INDEX 1
#define SOL3_INDEX 2
#define SOL4_INDEX 3

// Enclosure
#define ENCLOSURE_TEMP 20
#define ENCLOSURE_TEMP_THRESHOLD 5
#define COOLING_ENGAGED 30
#define COOLING_THRESHOLD 5

// Pneumatics

#define PNEUMATICS_THRESHOLD 3 // Margin of acceptable error on ideal value

#define LOWPRESSURE_UNARMED_MIN 0.0
#define LOWPRESSURE_UNARMED_MAX 18
#define LOWPRESSURE_ENGAGED_MIN 215
#define LOWPRESSURE_ENGAGED_MAX 255

#define HIGHPRESSURE_ARMED_MAX 1725
#define HIGHPRESSURE_ARMED_MIN 1550

#define PRESSURE_TEMP_MIN 0
#define PRESSURE_TEMP_MAX 60 //C

#define COOLING_TEMP_MIN 10
#define COOLING_TEMP_MAX 30



//


#define ATMOSPHERE_THRESHOLD 5.0f


#endif //FLIGHTCOMPUTER_SENSORCONFIG_H
