# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PodCommand.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import States_pb2 as States__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='PodCommand.proto',
  package='pds',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10PodCommand.proto\x12\x03pds\x1a\x0cStates.proto\"\x93\x02\n\npodCommand\x12\x38\n\x16\x63ontrolsInterfaceState\x18\x01 \x01(\x0e\x32\x18.ControlsInterfaceStates\x12\"\n\x0emanualPodState\x18\x02 \x01(\x0e\x32\n.PodStates\x12.\n\x14manualBrakeNodeState\x18\x03 \x01(\x0e\x32\x10.BrakeNodeStates\x12&\n\x10manualMotorState\x18\x04 \x01(\x0e\x32\x0c.MotorStates\x12,\n\x13manualLvdcNodeState\x18\x05 \x01(\x0e\x32\x0f.LvdcNodeStates\x12!\n\x19\x61utomaticStateTransitions\x18\x06 \x01(\x08')
  ,
  dependencies=[States__pb2.DESCRIPTOR,])




_PODCOMMAND = _descriptor.Descriptor(
  name='podCommand',
  full_name='pds.podCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='controlsInterfaceState', full_name='pds.podCommand.controlsInterfaceState', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manualPodState', full_name='pds.podCommand.manualPodState', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manualBrakeNodeState', full_name='pds.podCommand.manualBrakeNodeState', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manualMotorState', full_name='pds.podCommand.manualMotorState', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manualLvdcNodeState', full_name='pds.podCommand.manualLvdcNodeState', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='automaticStateTransitions', full_name='pds.podCommand.automaticStateTransitions', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=315,
)

_PODCOMMAND.fields_by_name['controlsInterfaceState'].enum_type = States__pb2._CONTROLSINTERFACESTATES
_PODCOMMAND.fields_by_name['manualPodState'].enum_type = States__pb2._PODSTATES
_PODCOMMAND.fields_by_name['manualBrakeNodeState'].enum_type = States__pb2._BRAKENODESTATES
_PODCOMMAND.fields_by_name['manualMotorState'].enum_type = States__pb2._MOTORSTATES
_PODCOMMAND.fields_by_name['manualLvdcNodeState'].enum_type = States__pb2._LVDCNODESTATES
DESCRIPTOR.message_types_by_name['podCommand'] = _PODCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

podCommand = _reflection.GeneratedProtocolMessageType('podCommand', (_message.Message,), dict(
  DESCRIPTOR = _PODCOMMAND,
  __module__ = 'PodCommand_pb2'
  # @@protoc_insertion_point(class_scope:pds.podCommand)
  ))
_sym_db.RegisterMessage(podCommand)


# @@protoc_insertion_point(module_scope)
