/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sat Jul 13 10:58:06 2019. */

#include "Paradigm.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const bool PodCommand_hasCommand_default = false;
const int32_t FlightConfig_pdsTelemetryPort_default = 7000;
const int32_t FlightConfig_commandPort_default = 6000;
const int32_t FlightConfig_heartbeatTimeout_default = 10000;
const uint64_t FlightConfig_nodePort_default = 5555ull;
const uint64_t FlightConfig_nodeTimeout_default = 2000ull;
const uint64_t FlightConfig_brakeNodeServerPort_default = 5550ull;
const int32_t FlightConfig_pdsUpdateFreq_default = 100;
const int32_t FlightConfig_brakeNodeUpdateFreq_default = 20;
const int32_t FlightConfig_enclosureNodeServerNumber_default = 5552;
const int32_t FlightConfig_lvdcNodeServerNumber_default = 5551;


const pb_field_t PodCommand_fields[14] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, PodCommand, controlsInterfaceState, controlsInterfaceState, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, PodCommand, manualPodState, controlsInterfaceState, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, PodCommand, manualBrakeNodeState, manualPodState, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, PodCommand, manualMotorState, manualBrakeNodeState, 0),
    PB_FIELD(  5, UENUM   , OPTIONAL, STATIC  , OTHER, PodCommand, manualLvdcNodeState, manualMotorState, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, PodCommand, automaticStateTransitions, manualLvdcNodeState, 0),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, PodCommand, hasCommand, automaticStateTransitions, &PodCommand_hasCommand_default),
    PB_FIELD(  8, INT32   , REPEATED, CALLBACK, OTHER, PodCommand, solenoidConfiguration, hasCommand, 0),
    PB_FIELD(  9, INT32   , REPEATED, CALLBACK, OTHER, PodCommand, powerRailConfiguration, solenoidConfiguration, 0),
    PB_FIELD( 10, INT32   , REPEATED, CALLBACK, OTHER, PodCommand, sensorOverrideConfiguration, powerRailConfiguration, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, PodCommand, motorTorque, sensorOverrideConfiguration, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, PodCommand, flightDistance, motorTorque, 0),
    PB_FIELD( 13, UINT32  , OPTIONAL, STATIC  , OTHER, PodCommand, maxFlightTime, flightDistance, 0),
    PB_LAST_FIELD
};

const pb_field_t Telemetry_fields[78] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, Telemetry, podState, podState, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, Telemetry, brakeNodeState, podState, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, Telemetry, motorState, brakeNodeState, 0),
    PB_FIELD(  4, UENUM   , OPTIONAL, STATIC  , OTHER, Telemetry, controlsInterfaceState, motorState, 0),
    PB_FIELD(  5, UENUM   , OPTIONAL, STATIC  , OTHER, Telemetry, inverterState, controlsInterfaceState, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, missionTime, inverterState, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, flightTime, missionTime, 0),
    PB_FIELD(  8, INT32   , REPEATED, CALLBACK, OTHER, Telemetry, heartbeatFlags, flightTime, 0),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, podPosition, heartbeatFlags, 0),
    PB_FIELD( 10, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, podVelocity, podPosition, 0),
    PB_FIELD( 11, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, podAccelerationX, podVelocity, 0),
    PB_FIELD( 16, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, tachometerVelocity, podAccelerationX, 0),
    PB_FIELD( 17, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, resolverVelocity, tachometerVelocity, 0),
    PB_FIELD( 18, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, maxIgbtTemperature, resolverVelocity, 0),
    PB_FIELD( 19, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, gateDriverTemperature, maxIgbtTemperature, 0),
    PB_FIELD( 20, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, inverterControlBoardTemperature, gateDriverTemperature, 0),
    PB_FIELD( 21, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, motorTemperature, inverterControlBoardTemperature, 0),
    PB_FIELD( 22, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, inverterBusVoltage, motorTemperature, 0),
    PB_FIELD( 23, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, inverterVoltages, inverterBusVoltage, 0),
    PB_FIELD( 24, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, inverterCurrents, inverterVoltages, 0),
    PB_FIELD( 25, UENUM   , OPTIONAL, STATIC  , OTHER, Telemetry, batteryManagementState, inverterCurrents, 0),
    PB_FIELD( 26, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, hvBatteryPackVoltage, batteryManagementState, 0),
    PB_FIELD( 27, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, hvBatteryPackCurrent, hvBatteryPackVoltage, 0),
    PB_FIELD( 28, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, hvBatteryPackMaxCellTemperature, hvBatteryPackCurrent, 0),
    PB_FIELD( 29, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, hvBatteryPackMinimumCellVoltage, hvBatteryPackMaxCellTemperature, 0),
    PB_FIELD( 30, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, hvBatteryPackMaxCellVoltage, hvBatteryPackMinimumCellVoltage, 0),
    PB_FIELD( 31, UENUM   , OPTIONAL, STATIC  , OTHER, Telemetry, breakNodePerceivedPodState, hvBatteryPackMaxCellVoltage, 0),
    PB_FIELD( 32, BOOL    , OPTIONAL, STATIC  , OTHER, Telemetry, solenoid1, breakNodePerceivedPodState, 0),
    PB_FIELD( 33, BOOL    , OPTIONAL, STATIC  , OTHER, Telemetry, solenoid2, solenoid1, 0),
    PB_FIELD( 34, BOOL    , OPTIONAL, STATIC  , OTHER, Telemetry, solenoid3, solenoid2, 0),
    PB_FIELD( 35, BOOL    , OPTIONAL, STATIC  , OTHER, Telemetry, solenoid4, solenoid3, 0),
    PB_FIELD( 38, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, highPressure, solenoid4, 0),
    PB_FIELD( 39, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, lowPressure1, highPressure, 0),
    PB_FIELD( 40, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, lowPressure2, lowPressure1, 0),
    PB_FIELD( 41, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, lowPressure3, lowPressure2, 0),
    PB_FIELD( 42, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, lowPressure4, lowPressure3, 0),
    PB_FIELD( 43, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, pressureVesselTemperature, lowPressure4, 0),
    PB_FIELD( 44, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, enclosurePressure, pressureVesselTemperature, 0),
    PB_FIELD( 45, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, enclosureTemperature, enclosurePressure, 0),
    PB_FIELD( 46, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railDisplacementY, enclosureTemperature, 0),
    PB_FIELD( 48, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, tubePressure, railDisplacementY, 0),
    PB_FIELD( 49, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, coolantPressure1, tubePressure, 0),
    PB_FIELD( 50, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, coolantPressure2, coolantPressure1, 0),
    PB_FIELD( 51, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, coolantPressure3, coolantPressure2, 0),
    PB_FIELD( 52, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, coolantTemperature, coolantPressure3, 0),
    PB_FIELD( 53, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, railTemperature, coolantTemperature, 0),
    PB_FIELD( 54, UENUM   , OPTIONAL, STATIC  , OTHER, Telemetry, lvdcNodeState, railTemperature, 0),
    PB_FIELD( 55, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, pack1Voltage, lvdcNodeState, 0),
    PB_FIELD( 56, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, pack2Voltage, pack1Voltage, 0),
    PB_FIELD( 57, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, pack1Current, pack2Voltage, 0),
    PB_FIELD( 58, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, pack2Current, pack1Current, 0),
    PB_FIELD( 59, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, rail1Voltage, pack2Current, 0),
    PB_FIELD( 60, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, rail2Voltage, rail1Voltage, 0),
    PB_FIELD( 61, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, rail3Voltage, rail2Voltage, 0),
    PB_FIELD( 62, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, rail4Voltage, rail3Voltage, 0),
    PB_FIELD( 63, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railCurrentSensor1, rail4Voltage, 0),
    PB_FIELD( 64, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railCurrentSensor2, railCurrentSensor1, 0),
    PB_FIELD( 65, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railCurrentSensor3, railCurrentSensor2, 0),
    PB_FIELD( 66, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railCurrentSensor4, railCurrentSensor3, 0),
    PB_FIELD( 67, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railCurrentSensor5, railCurrentSensor4, 0),
    PB_FIELD( 68, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railCurrentSensor6, railCurrentSensor5, 0),
    PB_FIELD( 69, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railCurrentSensor7, railCurrentSensor6, 0),
    PB_FIELD( 70, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railCurrentSensor8, railCurrentSensor7, 0),
    PB_FIELD( 71, INT32   , REPEATED, CALLBACK, OTHER, Telemetry, heartbeatValues, railCurrentSensor8, 0),
    PB_FIELD( 72, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railVoltageFlag, heartbeatValues, 0),
    PB_FIELD( 73, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, railCurrentFlag, railVoltageFlag, 0),
    PB_FIELD( 74, UINT32  , OPTIONAL, STATIC  , OTHER, Telemetry, motorTorque, railCurrentFlag, 0),
    PB_FIELD( 75, UINT32  , OPTIONAL, STATIC  , OTHER, Telemetry, flightDistance, motorTorque, 0),
    PB_FIELD( 76, UINT32  , OPTIONAL, STATIC  , OTHER, Telemetry, maxFlightTime, flightDistance, 0),
    PB_FIELD( 77, STRING  , REPEATED, CALLBACK, OTHER, Telemetry, updateMessages, maxFlightTime, 0),
    PB_FIELD( 78, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, inverterHeartbeat, updateMessages, 0),
    PB_FIELD( 79, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, hvBatteryPackStateOfCharge, inverterHeartbeat, 0),
    PB_FIELD( 80, INT32   , OPTIONAL, STATIC  , OTHER, Telemetry, motorSpeed, hvBatteryPackStateOfCharge, 0),
    PB_FIELD( 81, UINT32  , OPTIONAL, STATIC  , OTHER, Telemetry, tachRpm, motorSpeed, 0),
    PB_FIELD( 82, UINT32  , OPTIONAL, STATIC  , OTHER, Telemetry, irRpm, tachRpm, 0),
    PB_FIELD( 83, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, tachDistance, irRpm, 0),
    PB_FIELD( 84, FLOAT   , OPTIONAL, STATIC  , OTHER, Telemetry, irDistance, tachDistance, 0),
    PB_LAST_FIELD
};

const pb_field_t FcToBrakeNode_fields[7] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, FcToBrakeNode, packetNum, packetNum, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, FcToBrakeNode, nodeState, packetNum, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, FcToBrakeNode, solenoid1Config, nodeState, 0),
    PB_FIELD(  4, BOOL    , OPTIONAL, STATIC  , OTHER, FcToBrakeNode, solenoid2Config, solenoid1Config, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, FcToBrakeNode, solenoid3Config, solenoid2Config, 0),
    PB_FIELD(  6, BOOL    , OPTIONAL, STATIC  , OTHER, FcToBrakeNode, solenoid4Config, solenoid3Config, 0),
    PB_LAST_FIELD
};

const pb_field_t FcToLvdcNode_fields[4] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, FcToLvdcNode, packetNum, packetNum, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, FcToLvdcNode, podState, packetNum, 0),
    PB_FIELD(  3, UENUM   , OPTIONAL, STATIC  , OTHER, FcToLvdcNode, manualNodeState, podState, 0),
    PB_LAST_FIELD
};

const pb_field_t DtsNodeToFc_fields[9] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DtsNodeToFc, packetNum, packetNum, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, DtsNodeToFc, brakeNodeState, packetNum, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, DtsNodeToFc, brakeSolenoidState, brakeNodeState, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, DtsNodeToFc, ventSolenoidState, brakeSolenoidState, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, DtsNodeToFc, rotorTemperature, ventSolenoidState, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, DtsNodeToFc, pneumaticTemperature, rotorTemperature, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, DtsNodeToFc, tankPressure, pneumaticTemperature, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, DtsNodeToFc, brakePressure, tankPressure, 0),
    PB_LAST_FIELD
};

const pb_field_t EnclosureNodeToFc_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, EnclosureNodeToFc, packetNum, packetNum, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, EnclosureNodeToFc, enclosurePressure, packetNum, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, EnclosureNodeToFc, enclosureTemperature, enclosurePressure, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, EnclosureNodeToFc, coolantPressure1, enclosureTemperature, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, EnclosureNodeToFc, coolantPressure2, coolantPressure1, 0),
    PB_LAST_FIELD
};

const pb_field_t LvdcNodeToFc_fields[17] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, LvdcNodeToFc, packetNum, packetNum, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, state, packetNum, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, highPowerPackVoltage, state, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, lowPowerPackVoltage, highPowerPackVoltage, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, highPowerPackCurrent, lowPowerPackVoltage, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, lowPowerPackCurrent, highPowerPackCurrent, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, lowPower5Voltage, lowPowerPackCurrent, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, lowPower12Voltage, lowPower5Voltage, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, highPower12Voltage, lowPower12Voltage, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, lowPower24Voltage, highPower12Voltage, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, lowPower5Current, lowPower24Voltage, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, lowPower12Current, lowPower5Current, 0),
    PB_FIELD( 13, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, nodeCurrent, lowPower12Current, 0),
    PB_FIELD( 14, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, inverterCurrent, nodeCurrent, 0),
    PB_FIELD( 15, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, cooling1Current, inverterCurrent, 0),
    PB_FIELD( 16, FLOAT   , REQUIRED, STATIC  , OTHER, LvdcNodeToFc, cooling2Current, cooling1Current, 0),
    PB_LAST_FIELD
};

const pb_field_t BrakeNodeToFc_fields[14] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, BrakeNodeToFc, packetNum, packetNum, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, state, packetNum, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, solenoid1, state, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, solenoid2, solenoid1, 0),
    PB_FIELD(  5, BOOL    , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, solenoid3, solenoid2, 0),
    PB_FIELD(  6, BOOL    , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, solenoid4, solenoid3, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, highPressure, solenoid4, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, lowPressure1, highPressure, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, lowPressure2, lowPressure1, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, lowPressure3, lowPressure2, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, lowPressureCommon, lowPressure3, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, pneumaticTemperature, lowPressureCommon, 0),
    PB_FIELD( 13, FLOAT   , REQUIRED, STATIC  , OTHER, BrakeNodeToFc, coolantTemperature, pneumaticTemperature, 0),
    PB_LAST_FIELD
};

const pb_field_t FlightConfig_fields[14] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, FlightConfig, retrievalTimeout, retrievalTimeout, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, FlightConfig, pdsTelemetryPort, retrievalTimeout, &FlightConfig_pdsTelemetryPort_default),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, FlightConfig, commandPort, pdsTelemetryPort, &FlightConfig_commandPort_default),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, FlightConfig, heartbeatTimeout, commandPort, &FlightConfig_heartbeatTimeout_default),
    PB_FIELD(  5, STRING  , OPTIONAL, CALLBACK, OTHER, FlightConfig, podDriver, heartbeatTimeout, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, CALLBACK, OTHER, FlightConfig, controlLaptopIpAddr, podDriver, 0),
    PB_FIELD(  7, UINT64  , OPTIONAL, STATIC  , OTHER, FlightConfig, nodePort, controlLaptopIpAddr, &FlightConfig_nodePort_default),
    PB_FIELD(  8, UINT64  , OPTIONAL, STATIC  , OTHER, FlightConfig, nodeTimeout, nodePort, &FlightConfig_nodeTimeout_default),
    PB_FIELD(  9, UINT64  , OPTIONAL, STATIC  , OTHER, FlightConfig, brakeNodeServerPort, nodeTimeout, &FlightConfig_brakeNodeServerPort_default),
    PB_FIELD( 10, INT32   , OPTIONAL, STATIC  , OTHER, FlightConfig, pdsUpdateFreq, brakeNodeServerPort, &FlightConfig_pdsUpdateFreq_default),
    PB_FIELD( 11, INT32   , OPTIONAL, STATIC  , OTHER, FlightConfig, brakeNodeUpdateFreq, pdsUpdateFreq, &FlightConfig_brakeNodeUpdateFreq_default),
    PB_FIELD( 12, INT32   , OPTIONAL, STATIC  , OTHER, FlightConfig, enclosureNodeServerNumber, brakeNodeUpdateFreq, &FlightConfig_enclosureNodeServerNumber_default),
    PB_FIELD( 13, INT32   , OPTIONAL, STATIC  , OTHER, FlightConfig, lvdcNodeServerNumber, enclosureNodeServerNumber, &FlightConfig_lvdcNodeServerNumber_default),
    PB_LAST_FIELD
};

const pb_field_t DefaultFcToNode_fields[2] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, DefaultFcToNode, podState, podState, 0),
    PB_LAST_FIELD
};









/* @@protoc_insertion_point(eof) */
