#ifndef FLIGHTCOMPUTER_THREADMONITORSTATUS_H
#define FLIGHTCOMPUTER_THREADMONITORSTATUS_H

enum class ThreadMonitorStats
{
  Active,
  Busy,
  Non_Responsive,
  Danger,
};

#endif //FLIGHTCOMPUTER_THREADMONITORSTATUS_H
