# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NodeTelem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NodeTelem.proto',
  package='fc',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fNodeTelem.proto\x12\x02\x66\x63\"\x8d\x03\n\rbrakeNodeData\x12\n\n\x02id\x18\x01 \x02(\x05\x12/\n\x05state\x18\x0e \x01(\x0e\x32 .fc.brakeNodeData.breakNodeState\x12\x0c\n\x04sol1\x18\x02 \x01(\x08\x12\x0c\n\x04sol2\x18\x03 \x01(\x08\x12\x0c\n\x04sol3\x18\x04 \x01(\x08\x12\x0c\n\x04sol4\x18\x05 \x01(\x08\x12\x0c\n\x04sol5\x18\x06 \x01(\x08\x12\x0c\n\x04sol6\x18\x07 \x01(\x08\x12\n\n\x02hp\x18\x08 \x01(\x05\x12\x0b\n\x03lp1\x18\t \x01(\x05\x12\x0b\n\x03lp2\x18\n \x01(\x05\x12\x0b\n\x03lp3\x18\x0b \x01(\x05\x12\x0b\n\x03lp4\x18\x0c \x01(\x05\x12\x0c\n\x04temp\x18\r \x01(\x05\"\x9c\x01\n\x0e\x62reakNodeState\x12\x0e\n\nbnsBooting\x10\x00\x12\x0e\n\nbnsStandby\x10\x01\x12\r\n\tbnsArming\x10\x02\x12\x0c\n\x08\x62nsArmed\x10\x03\x12\r\n\tbnsFlight\x10\x04\x12\x0e\n\nbnsBraking\x10\x05\x12\x0e\n\nbnsVenting\x10\x06\x12\x10\n\x0c\x62nsRetrieval\x10\x07\x12\x0c\n\x08\x62nsError\x10\x08')
)



_BRAKENODEDATA_BREAKNODESTATE = _descriptor.EnumDescriptor(
  name='breakNodeState',
  full_name='fc.brakeNodeData.breakNodeState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='bnsBooting', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bnsStandby', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bnsArming', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bnsArmed', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bnsFlight', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bnsBraking', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bnsVenting', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bnsRetrieval', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='bnsError', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=265,
  serialized_end=421,
)
_sym_db.RegisterEnumDescriptor(_BRAKENODEDATA_BREAKNODESTATE)


_BRAKENODEDATA = _descriptor.Descriptor(
  name='brakeNodeData',
  full_name='fc.brakeNodeData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='fc.brakeNodeData.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='fc.brakeNodeData.state', index=1,
      number=14, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sol1', full_name='fc.brakeNodeData.sol1', index=2,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sol2', full_name='fc.brakeNodeData.sol2', index=3,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sol3', full_name='fc.brakeNodeData.sol3', index=4,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sol4', full_name='fc.brakeNodeData.sol4', index=5,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sol5', full_name='fc.brakeNodeData.sol5', index=6,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sol6', full_name='fc.brakeNodeData.sol6', index=7,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hp', full_name='fc.brakeNodeData.hp', index=8,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lp1', full_name='fc.brakeNodeData.lp1', index=9,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lp2', full_name='fc.brakeNodeData.lp2', index=10,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lp3', full_name='fc.brakeNodeData.lp3', index=11,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lp4', full_name='fc.brakeNodeData.lp4', index=12,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='fc.brakeNodeData.temp', index=13,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BRAKENODEDATA_BREAKNODESTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=421,
)

_BRAKENODEDATA.fields_by_name['state'].enum_type = _BRAKENODEDATA_BREAKNODESTATE
_BRAKENODEDATA_BREAKNODESTATE.containing_type = _BRAKENODEDATA
DESCRIPTOR.message_types_by_name['brakeNodeData'] = _BRAKENODEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

brakeNodeData = _reflection.GeneratedProtocolMessageType('brakeNodeData', (_message.Message,), dict(
  DESCRIPTOR = _BRAKENODEDATA,
  __module__ = 'NodeTelem_pb2'
  # @@protoc_insertion_point(class_scope:fc.brakeNodeData)
  ))
_sym_db.RegisterMessage(brakeNodeData)


# @@protoc_insertion_point(module_scope)
