// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PodTelem.proto

#ifndef PROTOBUF_INCLUDED_PodTelem_2eproto
#define PROTOBUF_INCLUDED_PodTelem_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_PodTelem_2eproto 

namespace protobuf_PodTelem_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_PodTelem_2eproto
namespace pds {
class telemetry;
class telemetryDefaultTypeInternal;
extern telemetryDefaultTypeInternal _telemetry_default_instance_;
}  // namespace pds
namespace google {
namespace protobuf {
template<> ::pds::telemetry* Arena::CreateMaybeMessage<::pds::telemetry>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace pds {

// ===================================================================

class telemetry : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pds.telemetry) */ {
 public:
  telemetry();
  virtual ~telemetry();

  telemetry(const telemetry& from);

  inline telemetry& operator=(const telemetry& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  telemetry(telemetry&& from) noexcept
    : telemetry() {
    *this = ::std::move(from);
  }

  inline telemetry& operator=(telemetry&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const telemetry& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const telemetry* internal_default_instance() {
    return reinterpret_cast<const telemetry*>(
               &_telemetry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(telemetry* other);
  friend void swap(telemetry& a, telemetry& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline telemetry* New() const final {
    return CreateMaybeMessage<telemetry>(NULL);
  }

  telemetry* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<telemetry>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const telemetry& from);
  void MergeFrom(const telemetry& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(telemetry* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pds.telemetry)
 private:
  void set_has_id();
  void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 id_;
  friend struct ::protobuf_PodTelem_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// telemetry

// required int32 id = 1;
inline bool telemetry::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void telemetry::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void telemetry::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void telemetry::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 telemetry::id() const {
  // @@protoc_insertion_point(field_get:pds.telemetry.id)
  return id_;
}
inline void telemetry::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:pds.telemetry.id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pds

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_PodTelem_2eproto
